# https://cloud.google.com/appengine/docs/python/config/appref
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /.*
  script: Enigma.app
  secure: always

libraries:
- name: webapp2
  version: latest
  